logging:
  level:
    org:
      hibernate: ${LOG_HIBERNATE:INFO}
      springframework:
        root: ${LOG_ROOT:INFO}
        web: ${LOG_WEB:INFO}
        security: ${LOG_SEC:INFO}
        transaction:
          interceptor: ${LOG_TRANSACTION:INFO}
        orm:
          jpa: ${LOG_JPA:INFO}

spring:
  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
