spring:
  application:
    name: BancoDigitalP2
  profiles:
    active: dev

server:
  port: ${BD_PORT:9999}

application:
  bank_name: ${BANK_NAME:BancoBR}
  timezone:
    zone_id: ${TIMEZONE:America/Sao_Paulo}