application:
  external:
    viacep:
      url: ${CEP_SERVICE_URL:https://viacep.com.br/ws/%s/json/}
      timeout_in_millis: ${CEP_SERVICE_TIMEOUT:5000}
  name: ${BANK_NAME:BancoBR}
  timezone:
    zone_id: ${TIMEZONE:America/Sao_Paulo}

spring:
  application:
    name: BancoDigitalP2
  profiles:
    active: dev

server:
  port: ${BD_PORT:9999}
